### ISSUE TITLE
Extend characterset for project names

### ISSUE THREAD

**Issue by xla** [radicle-dev/registry-spec#15]
While there is strong reason to have quite a restrictive character set for top-level ids (i.e. orgs and users), to avoid confusion and trickery. This might not apply to project names which have broader range of naming conventions for branding reasons or to clearly communicate what ecosystem they belong to. Proposed validation are:

* Must be between **1** and **32** characters
* Must be ASCII-encoded
* Musty only contain `a-zA-Z0-9_-.`
* Must not eqal `.`
* Must not equal `..`

We need to address tho, what the implications are for case sensitivity. @cloudhead rightfully pointed out that we don't want to allow for `cloudhead/rx` and `cloudhead/Rx` to exist side by side and there is no precedence where that is allowed on other platforms. Yet these user provide handles might be worth preserving. Which in case will have implications on the storage and therefor not be feasible. It's the most important point this issue should clarify.

**Comment by cloudhead** [comment]
Thanks, I think this makes sense. The only rule I would loosen is the 4th one, since the only thing we should really avoid is collision with the `.` and `..` file in unix-based OSes, we can actually check `name != "." && name != ".."`. From what I can tell, this is also what github does.

As for the case-insensitivity story, for projects it should be easy because we store a handle in the project metadata, and this handle could have uppercase letters. This is the handle we should show to users I guess. In the registry, we can store it all lowercase however.

For user ids, it's a different story (and may be more complicated) but let's keep this issue around project names.

**Comment by xla** [comment]
> Thanks, I think this makes sense. The only rule I would loosen is the 4th one, since the only thing we should really avoid is collision with the `.` and `..` file in unix-based OSes, we can actually check `name != "." && name != ".."`. From what I can tell, this is also what github does.

Adjusted the list. Still not sure about leading and trailing `.`s. I know you like to keep file semantics, but I don't understand where that relation is coming from, as this is not a file tree we are looking at. Maybe you can expand on your thinking.

> As for the case-insensitivity story, for projects it should be easy because we store a handle in the project metadata, and this handle could have uppercase letters. This is the handle we should show to users I guess. In the registry, we can store it all lowercase however.

Intuitively I'd follow that line of thought. Yet this assumes there will always be project metadata that comes with a project on the registry. and we guarantee it to be replicated whenever a project is displayed. While already a hard guarantee to make in the application layer, it will never be the case when consuming Registry state directly. If that is okay for use-case and we are aware of the subtle change in identity of a project, we can settle on it.

**Comment by cloudhead** [comment]
> I don't understand where that relation is coming from, as this is not a file tree we are looking at. Maybe you can expand on your thinking.

Ah, sorry. The reason I bring it up is that if we want local checkouts of these projects, while preserving the name, eg. `$HOME/src/cloudhead/radicle`, it will cause problems for projects that don't have valid regular file names, eg. `..`.

>  If that is okay for use-case and we are aware of the subtle change in identity of a project, we can settle on it.

I see. Yeah tbh I'm okay with it because in the registry we have very very little anyway. The "display name" seems like a luxury at that point, and definitely an end user feature, not a protocol-level detail.

**Comment by xla** [comment]
> Ah, sorry. The reason I bring it up is that if we want local checkouts of these projects, while preserving the name, eg. `$HOME/src/cloudhead/radicle`, it will cause problems for projects that don't have valid regular file names, eg. `..`.

AFAIK checkouts are a concern of the CoCo domain and likely be governaned by the project handle stored as metadata there. I don't see a case where you cancheck out a project without having the CoCo context.

> I see. Yeah tbh I'm okay with it because in the registry we have very very little anyway. The "display name" seems like a luxury at that point, and definitely an end user feature, not a protocol-level detail.

Sound to me.
